### ISSUE TITLE
Expand classes

### ISSUE THREAD

**Issue by dreaming-augustin** [dedalozzo/converter#4]
Thanks for this little converter. It's simple and does the job.

It'd be nice to have a programmable support for HTML classes. 
Suppose I have HTML which includes classes:
`<strong class="notice">Important information</strong>`
We could have a framework where we could program instances of classes, and how to render them in BBCode.
For example, class="notice" could be wrapped in red colour:
`[b][color=#FF0000]Important information[/color][/b]`

The library could thus be made class aware. The user could register a class and tell the library how to render it. When the converter finds a class, it looks up if it is among registered classes, and handles it appropriately.

**Comment by dreaming-augustin** [comment]
It should also work for tags that are currently stripped, like `<p>` or `<span>`.

`<span class="notice">Important information</span>`
would become:
`[color=#FF0000]Important information[/color]`

**Comment by dreaming-augustin** [comment]
The major hurdle I see is that the converter does not seem to be aware of pairs of tag, so it wouldn't know where to add the closing bbcode tag for the HTML element with a given class.

Implementing what I propose would require the converter to be DOM aware. I am aware that it would require a major refactor of the current code.... :-/

**Comment by dedalozzo** [comment]
Hi,

I have written this library to convert over 20.000 articles originally written using HTML and BBCode and I'm aware that HTML parsing shouldn't be done using regex, but I didn't want to write a parser from scratch and the articles I had to convert are not HTML document, they are just text files using some HTML tags. And yep, the library did the job.

To achieve the goals you have in mind the library should use the pattern Command and maybe implement the Decorator pattern as well. It's not a big work to refactor it, but sincerely I don't have time, neither I'm interested to do that. I have too much things going on. But feel free to fork the project.
